### <mark> Word Embeddings

    Word Embeddings in NLP is a technique where individual words are represented as real-valued vectors in a lower-dimensional space and captures inter-word semantics.
    Word Embedding or Word Vector is a numeric vector input that represents a word in a lower-dimensional space. It allows words with similar meaning to have a similar representation.
    They can also approximate meaning. A word vector with 50 values can represent 50 unique features.
    
Advantages:
       
    Gives real valued vectors in a lower dimensional space
    Captures inter word semantics
    Reduces dimentionality
    Helps predict words around a word
    Methods such as BoW, TD-IDF rely on the word count in a sentence but they do not save any semantic info.
    Almost all modern nlp applications start with embedding layer
    
Disadvantages:
    
    memory intensive
    cannot distinguish between homophones. eg., brake/break
    
Approaches/Techniques
    
    Word2Vec
        cbow
        skip-gram
    GloVe

In [3]:
# !python -m spacy download en_core_web_lg

In [ ]:
import spacy
nlp = spacy.load('en_core_web_lg')  

In [6]:
nlp(u'simple').vector

array([ 7.1729e-01,  1.3588e+00, -4.9205e-02,  1.5158e+00,  1.3116e+00,
       -2.1567e+00,  3.6357e+00,  1.8520e+00, -5.0275e+00,  2.1978e+00,
        7.0311e+00,  1.5903e+00, -4.3006e+00,  2.3341e+00,  3.9661e+00,
       -7.5158e-01,  2.3964e+00, -1.1702e+00, -2.1844e-02, -1.7807e-01,
       -2.1027e+00,  3.0961e+00, -7.9090e-03, -2.0693e-01, -2.9393e+00,
       -1.2823e+00,  1.5543e-02,  9.5328e-01, -3.2584e+00,  3.7656e+00,
       -5.0492e-01, -3.7038e+00,  8.3301e-01, -1.7658e+00,  2.6687e+00,
       -2.5927e+00,  1.3625e+00,  1.1390e+00,  3.7002e+00,  1.7027e+00,
        3.2552e+00, -2.4619e+00, -1.7036e+00, -3.1906e+00, -5.6705e-01,
        4.0653e+00,  5.0637e+00, -4.4248e+00, -2.4892e+00,  1.8204e+00,
       -1.2794e-02,  9.8560e-02,  3.9811e-01, -3.5691e+00, -3.4484e+00,
        1.6158e+00,  4.5479e+00,  6.7522e+00,  2.9260e-01,  8.7796e-01,
        2.5872e+00,  7.0159e-01, -1.2507e+00, -1.2619e+00, -1.5277e+00,
        3.1918e+00, -2.2707e+00, -9.8390e+00,  6.5251e-02, -3.09

In [5]:
nlp(u'queen').vector

array([ 2.167    ,  0.29991  , -3.1277   , -2.7817   , -0.26743  ,
        3.0804   , -2.6528   ,  0.59692  ,  0.12359  ,  4.8586   ,
        5.9099   , -5.0363   , -0.92574  ,  0.24834  ,  0.99726  ,
       -1.4138   , -1.6813   , -2.3217   ,  2.239    , -2.406    ,
       -3.1548   , -0.31535  ,  0.63494  ,  2.6102   ,  0.029033 ,
        0.36093  ,  0.82687  , -0.046114 ,  0.86223  , -1.539    ,
       -1.3586   , -4.2778   ,  0.92605  , -3.623    , -0.20905  ,
        0.40445  , -0.51169  , -0.18221  , -0.45019  ,  1.6452   ,
       -0.21377  , -0.013464 ,  1.3225   ,  2.6444   ,  2.8484   ,
       -1.8366   , -1.6336   ,  2.3608   ,  1.8614   ,  0.62935  ,
       -1.7363   , -1.2249   ,  0.012297 , -0.23621  ,  0.40521  ,
       -0.65902  , -2.3748   , -3.9021   ,  0.16969  ,  5.1174   ,
       -0.60783  , -3.2307   ,  2.2142   , -0.09337  , -0.64347  ,
       -2.0623   , -3.5153   , -3.5514   ,  3.1468   ,  2.199    ,
       -1.9324   ,  1.7778   , -0.98875  , -3.8789   , -1.6005

In [7]:
len(nlp(u'queen').vector)

300

In [13]:
import numpy as np
doc = nlp(u'who let the dogs out')
print(np.array(doc).shape)
doc.vector

(5,)


array([-1.25519991e+00,  3.38542414e+00, -3.04648018e+00,  6.03720009e-01,
        1.04830003e+00,  4.15392208e+00, -3.96093994e-01,  2.26865983e+00,
       -1.46673000e+00, -2.92162001e-01,  4.83446026e+00,  2.30411792e+00,
       -2.25753927e+00,  2.27109981e+00,  2.77898598e+00, -1.24686408e+00,
        2.15660882e+00, -3.63025212e+00, -5.77811956e-01, -3.85101366e+00,
        1.82344282e+00, -1.92588997e+00,  1.15956807e+00, -4.75785971e+00,
        1.64125407e+00, -2.13626191e-01, -1.96125603e+00,  4.45760012e-01,
       -3.84769857e-01,  7.90479958e-01,  1.83882010e+00, -2.90632010e+00,
        4.48359966e-01, -4.07026005e+00, -2.43132997e+00, -2.65275192e+00,
       -1.89988804e+00,  1.82103992e+00,  3.42263603e+00, -1.06763005e+00,
       -1.17767191e+00,  1.99106193e+00,  1.98964000e+00,  2.58064008e+00,
       -5.26899993e-01,  5.61385989e-01, -1.25947988e+00, -4.97865200e+00,
       -2.48386002e+00,  3.70113993e+00,  3.46220016e-01,  3.68628001e+00,
        6.64319992e-01, -

In [15]:
tokens = nlp(u'tiger dog pet')

for token1 in tokens:
    for token2 in tokens:
        print(token1.text, '\t', token2.text, '\t', token1.similarity(token2))

tiger 	 tiger 	 1.0
tiger 	 dog 	 0.42287227511405945
tiger 	 pet 	 0.31030499935150146
dog 	 tiger 	 0.42287227511405945
dog 	 dog 	 1.0
dog 	 pet 	 0.7856058478355408
pet 	 tiger 	 0.31030499935150146
pet 	 dog 	 0.7856058478355408
pet 	 pet 	 1.0


In [16]:
nlp(u'king').similarity(nlp(u'queen'))

0.6108841234425123

In [17]:
nlp(u'king').similarity(nlp(u'fish'))

0.210579704017407

In [21]:
nlp(u'queen').similarity(nlp(u'photo'))

0.06449755090975247

In [24]:
# similarity can be checked between sentences also,
# notice the similarity score to be high even if the sentences mean totally different

In [22]:
nlp(u'we love pizza').similarity(nlp(u'we hate pizza'))

0.9535042087197989

In [23]:
nlp(u'this place is awesome. I love it').similarity(nlp(u'this place is boring. I hate it'))

0.9799502109135215

In [25]:
len(nlp.vocab.vectors)

514157

In [26]:
nlp.vocab.vectors.shape

(514157, 300)

In [30]:
tokens = nlp(u'king dgks')

for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

king True 69.68691 False
dgks False 0.0 True


In [30]:
from scipy import spatial

cosine_similarity = lambda x, y: 1 - spatial.distance.cosine(x, y)

king = nlp.vocab['king'].vector
man = nlp.vocab['man'].vector
woman = nlp.vocab['woman'].vector

# Now we find the closest vector in the vocabulary to the result of "man" - "woman" + "queen"
new_vector = king - man + woman
computed_similarities = []

words = ['cat','apple','queen','castle','sea','shell','orange','phone' , 'tiffany'
         ,'angry','book','white','land','study','crown','prince','dog',
         'great','princess','elizabeth','wow','eat','dead','horrible']

for word in words:
    similarity = cosine_similarity(new_vector,nlp.vocab[word].vector)
    computed_similarities.append((word, similarity))

computed_similarities = sorted(computed_similarities, key=lambda item: -item[1])

for a,b in computed_similarities[:10] : 
    print(f'Word {a} , has similarity {b}')

Word queen , has similarity 0.7880843877792358
Word prince , has similarity 0.6401076912879944
Word princess , has similarity 0.6125636100769043
Word elizabeth , has similarity 0.4564860165119171
Word crown , has similarity 0.42476341128349304
Word castle , has similarity 0.3814162015914917
Word white , has similarity 0.32747429609298706
Word angry , has similarity 0.2994381785392761
Word sea , has similarity 0.2897905111312866
Word cat , has similarity 0.27486881613731384
